# Generated by Django 3.0.7 on 2021-02-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, unique=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=15)),
                ('longitude', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Comorbidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Comorbidade',
                'verbose_name_plural': 'Comorbidades',
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=10, unique=True)),
                ('descartado', models.CharField(blank=True, max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Teste',
                'verbose_name_plural': 'Testes',
            },
        ),
        migrations.CreateModel(
            name='Ubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ubs',
                'verbose_name_plural': 'Ubs',
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('residente', models.BooleanField(blank=True, default=True, max_length=1, verbose_name='Residente')),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('data_notificacao', models.DateField(blank=True, null=True)),
                ('confirmado', models.BooleanField(blank=True, default=True, verbose_name='Confirmado')),
                ('recuperado', models.BooleanField(blank=True, verbose_name='Recuperado')),
                ('obito', models.BooleanField(blank=True, verbose_name='Óbito')),
                ('internado', models.BooleanField(blank=True, verbose_name='Internado')),
                ('uti', models.BooleanField(blank=True, verbose_name='UTI')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('atualizado_em', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Bairro')),
                ('comorbidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Comorbidade')),
                ('ubs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Ubs')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ('criado_em',),
            },
        ),
    ]
