# Generated by Django 3.0.7 on 2021-02-16 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bairro_caso_comorbidade_teste_ubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.IntegerField()),
                ('conf_por_dia', models.IntegerField()),
                ('obito', models.IntegerField()),
                ('recuperado', models.IntegerField()),
                ('criado_em', models.DateField(default=datetime.datetime(2021, 2, 16, 17, 32, 49, 805883, tzinfo=utc), verbose_name='Criado em')),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Diario',
                'verbose_name_plural': 'Diarios',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_dia', models.DateField(blank=True, null=True)),
                ('media_conf', models.IntegerField()),
                ('tx_conf', models.FloatField()),
                ('media_obt', models.IntegerField()),
                ('tx_obt', models.FloatField()),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Media_dia',
                'verbose_name_plural': 'Medias',
            },
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=100)),
                ('confirmado', models.IntegerField()),
                ('obito', models.IntegerField()),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'periodos',
            },
        ),
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(blank=True, max_length=100)),
                ('taxa', models.FloatField()),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Semana',
                'verbose_name_plural': 'semanas',
            },
        ),
    ]
