# Generated by Django 3.0.7 on 2021-02-16 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diario_media_semana_taxa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 17, 35, 54, 671635, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
