# Generated by Django 3.0.7 on 2021-02-16 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210216_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taxa',
        ),
        migrations.AlterModelOptions(
            name='semana',
            options={'verbose_name': 'Semana_Epidemiologica', 'verbose_name_plural': 'Semana_Epidemiológica'},
        ),
        migrations.RenameField(
            model_name='semana',
            old_name='confirmado',
            new_name='conf_sm',
        ),
        migrations.RenameField(
            model_name='semana',
            old_name='obito',
            new_name='obt_sm',
        ),
        migrations.RenameField(
            model_name='semana',
            old_name='periodo',
            new_name='semana',
        ),
        migrations.AddField(
            model_name='semana',
            name='trans_sm',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 17, 43, 43, 132083, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
