# Generated by Django 3.0.7 on 2021-02-16 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210216_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefeitura',
            name='populacao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 18, 24, 38, 76686, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
