# Generated by Django 3.0.7 on 2021-02-16 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210216_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 18, 55, 46, 370768, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
