# Generated by Django 3.0.7 on 2021-03-11 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210216_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf_mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_mes', models.CharField(blank=True, max_length=100, unique=True)),
                ('conf_total_mes', models.IntegerField()),
                ('media_conf_mes', models.FloatField()),
                ('status_conf_mes', models.BooleanField(blank=True, default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'conf_mes',
                'verbose_name_plural': 'Conf_mes',
            },
        ),
        migrations.CreateModel(
            name='Obitos_mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obitos_mes', models.CharField(blank=True, max_length=100, unique=True)),
                ('obitos_total_mes', models.IntegerField()),
                ('media_obt_mes', models.FloatField()),
                ('status_obitos_mes', models.BooleanField(blank=True, default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'obitos_mes',
                'verbose_name_plural': 'Obitos_mes',
            },
        ),
        migrations.AlterModelOptions(
            name='diario',
            options={'verbose_name': 'Diario', 'verbose_name_plural': 'Informe_diário'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media_dia', 'verbose_name_plural': 'Media_móvel'},
        ),
        migrations.AlterModelOptions(
            name='semana',
            options={'verbose_name': 'Semana_Epidemiologica', 'verbose_name_plural': 'Semana_epidemiológica'},
        ),
        migrations.AlterModelOptions(
            name='teste',
            options={'verbose_name': 'Teste', 'verbose_name_plural': 'Teste_rápido'},
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 3, 11, 13, 9, 2, 559383, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
