# Generated by Django 3.0.7 on 2021-03-12 03:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210311_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conf_mes',
            old_name='conf_total_mes',
            new_name='total_conf_mes',
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 3, 12, 3, 35, 24, 230263, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
