# Generated by Django 3.0.7 on 2021-03-12 04:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210312_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obitos_mes',
            old_name='media_obt_mes',
            new_name='media_obitos_mes',
        ),
        migrations.RenameField(
            model_name='obitos_mes',
            old_name='obitos_total_mes',
            new_name='total_obitos_mes',
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 3, 12, 4, 7, 33, 42948, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
