# Generated by Django 3.0.7 on 2021-03-12 04:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210312_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 3, 12, 4, 7, 42, 878918, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
