# Generated by Django 3.1.7 on 2021-04-28 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210428_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf_mes',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 11, 20, 28, 4032, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 11, 20, 28, 1657, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='obitos_mes',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 11, 20, 28, 3441, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
