# Generated by Django 3.1.7 on 2021-05-13 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210428_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='isolado',
            field=models.BooleanField(blank=True, default=1, verbose_name='Isolado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conf_mes',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 16, 16, 25, 752364, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 16, 16, 25, 749993, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='obitos_mes',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 16, 16, 25, 751766, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
