# Generated by Django 3.1.7 on 2021-05-14 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210513_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf_mes',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 3, 33, 12, 257542, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 3, 33, 12, 255165, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='obitos_mes',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 3, 33, 12, 256931, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
