# Generated by Django 3.0.3 on 2021-05-14 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210514_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf_mes',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 13, 34, 42, 598092, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 13, 34, 42, 595610, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='obitos_mes',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 13, 34, 42, 597509, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
