# Generated by Django 3.0.3 on 2021-05-14 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210514_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='obt_por_dia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conf_mes',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 16, 11, 51, 340767, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 16, 11, 51, 337721, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='obitos_mes',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 5, 14, 16, 11, 51, 340190, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
