# Generated by Django 3.0.3 on 2021-11-17 03:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210516_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='comorbidade',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='ubs',
        ),
        migrations.DeleteModel(
            name='Conf_mes',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Obitos_mes',
        ),
        migrations.DeleteModel(
            name='Semana',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
        migrations.AddField(
            model_name='diario',
            name='desacartado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diario',
            name='isolado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diario',
            name='leito',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diario',
            name='realizado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diario',
            name='uti',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 11, 17, 3, 45, 20, 248238, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='prefeitura',
            name='uf',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Bairro',
        ),
        migrations.DeleteModel(
            name='Caso',
        ),
        migrations.DeleteModel(
            name='Comorbidade',
        ),
        migrations.DeleteModel(
            name='Ubs',
        ),
    ]
