# Generated by Django 3.0.3 on 2021-11-17 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20211117_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diario',
            old_name='leito',
            new_name='leito_positivo',
        ),
        migrations.RenameField(
            model_name='diario',
            old_name='uti',
            new_name='leito_suspeito',
        ),
        migrations.AddField(
            model_name='diario',
            name='uti_positivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diario',
            name='uti_suspeito',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 11, 17, 17, 31, 37, 466982, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
