# Generated by Django 3.0.3 on 2021-11-18 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20211118_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletim',
            options={'ordering': ['-upload_em'], 'verbose_name': 'Boletim', 'verbose_name_plural': 'Boletins'},
        ),
        migrations.AlterField(
            model_name='boletim',
            name='upload_em',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 21, 42, 19, 26259, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='criado_em',
            field=models.DateField(default=datetime.datetime(2021, 11, 18, 21, 42, 19, 25782, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
